In [20]:
import pandas as pd
import sqlalchemy
import mysql.connector

In [21]:
engine = sqlalchemy.create_engine("mysql+mysqlconnector://root:welcome@data@localhost:3306/sqlproject", echo = True)

In [31]:
%load_ext sql

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

In [32]:
%sql mysql+mysqlconnector://root:welcome@data@localhost:3306/sqlproject

In [33]:
%%sql

select * from coviddeath limit 5;

 * mysql+mysqlconnector://root:***@localhost:3306/sqlproject
5 rows affected.

[('AFG', 'Asia', 'Afghanistan', '24/02/20', 38928341, 1, 1, '', '', '', '', 0.026, 0.026, '', '', '', '', '', '', '', '', '', '', '', '', ''),
 ('AFG', 'Asia', 'Afghanistan', '25/02/20', 38928341, 1, 0, '', '', '', '', 0.026, 0.0, '', '', '', '', '', '', '', '', '', '', '', '', ''),
 ('AFG', 'Asia', 'Afghanistan', '26/02/20', 38928341, 1, 0, '', '', '', '', 0.026, 0.0, '', '', '', '', '', '', '', '', '', '', '', '', ''),
 ('AFG', 'Asia', 'Afghanistan', '27/02/20', 38928341, 1, 0, '', '', '', '', 0.026, 0.0, '', '', '', '', '', '', '', '', '', '', '', '', ''),
 ('AFG', 'Asia', 'Afghanistan', '28/02/20', 38928341, 1, 0, '', '', '', '', 0.026, 0.0, '', '', '', '', '', '', '', '', '', '', '', '', '')]

In [34]:
%%sql

select * from covidvaccination limit 5;

 * mysql+mysqlconnector://root:***@localhost:3306/sqlproject
5 rows affected.

[('AFG', 'Asia', 'Afghanistan', '24/02/20', 1, 1, '', '', '', '', 0.026, 0.026, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 8.33, 38928341, 54.422, 18.6, 2.581, 1.337, 1803.987, '', 597.029, 9.59, '', '', 37.746, 0.5, 64.83, 0.511),
 ('AFG', 'Asia', 'Afghanistan', '25/02/20', 1, 0, '', '', '', '', 0.026, 0.0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 8.33, 38928341, 54.422, 18.6, 2.581, 1.337, 1803.987, '', 597.029, 9.59, '', '', 37.746, 0.5, 64.83, 0.511),
 ('AFG', 'Asia', 'Afghanistan', '26/02/20', 1, 0, '', '', '', '', 0.026, 0.0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 8.33, 38928341, 54.422, 18.6, 2.581, 1.337, 1803.987, '', 597.029, 9.59, '', '', 37.746, 0.5, 64.83, 0.511),
 ('AFG', 'Asia', 'Afghanistan', '27/02/20', 1, 0, '', '', '', '', 0.026, 0.0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 8.33, 38928341, 54.422, 18.6, 2.581, 1.337, 1803.987, '', 597.029, 9.59, '', '', 37.746, 0.5, 64.83, 0.511),
 ('AFG', 'Asia', 'Afghanistan', '28/02/20', 1, 0, '', '', '', '', 0.026, 0.0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 8.33, 38928341, 54.422, 18.6, 2.581, 1.337, 1803.987, '', 597.029, 9.59, '', '', 37.746, 0.5, 64.83, 0.511)]

In [36]:
%%sql 

Select Count(*) From Coviddeath;

 * mysql+mysqlconnector://root:***@localhost:3306/sqlproject
1 rows affected.

[(85410,)]

In [37]:
%%sql 

Select Count(*) From Covidvaccination;

 * mysql+mysqlconnector://root:***@localhost:3306/sqlproject
1 rows affected.

[(28552,)]